styles.css

Improved the missing, fallen and arrested tags to match the velocity of the event with red being the most critical. Chnaged background color for accessibility reasons.

Improve styling and responsiveness.

---

index.html

Added a global cookies banner script

added Global cookie banner

---

README.md
data.json
js/scripts.js

[Feature Request](https://x.com/WesKambale/status/1815675219920507132)
- This commit introduces the "taken_time" field in the data.json file to record the time when a person was taken. 
- Two functions, parseCustomDateFormat() and getRelativeTime(), were added in scripts.js to deal with this new timestamp. 
- Both the JSON data structure and the README file were well updated to reflect these changes.

Add "taken_time" to indicate when someone was taken.

---

css/styles.css
index.html

added footer to index page, added footer css

added footer links for privacy and cookies in index file, updated footer CSS

---

index.html

Remove unnecessary code from the footer

Footer fixes

---

README.md

Previous PR messed up the relative path of an asset. This is a fix

fix(README): update the asset relative path in README.md

---

data.json

This is based on the earliest time an arrest was reported on Twitter.

feat: update the time taken

---

index.html

- Move closing body tag and JavaScript to the right location - avoid mulfunctioning
- Use semantic tags instead of divs - improves accessibility

Semantic html and tag re-arrangment for accessibility

---

index.html
src/css/styles.css

- CSS for positioning filter and search element
- More self explanatory css class names for html attributes

Center Filter and Search

---

index.html
src/css/styles.css

This PR adds a remanded status to represent missing persons who have been sent to jail as they await their next court dates.
It has also been added to the category filters such that a person can easily filter the remanded victims.

Add remanded status to represent missing persons sent to jail

---

data.json

Addresses issue https://github.com/wkambale/missingpersons/issues/74 with duplicate entries for the same human

Remove duplicate entry

---

index.html
src/css/styles.css

Fix the search sort component.

---

src/js/scripts.js

- fix issues we were seeing with the infinite scroll especially during search,
- Fixing infinite load keeps loading even when one's reached the end of the list
- the infinite scroll  is confusing UI, when there is no data, the user will wait thinking they have a data issue, if the spinner is loading but never stops.
-When I filter for released, the CSS is messed up
Resolves [#77 ](https://github.com/wkambale/missingpersons/issues/77)

- fix infinite scroll issues.

---

README.md

Expanded the contribution guidelines section to provide more detailed steps for reporting issues, expressing interest in issues, and contributing code. Added a new section on reviewing pull requests for better collaboration.

Refactor README.md to improve contribution guidelines

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

Introduced new GitHub templates for bug reports, feature requests, and pull requests to streamline issue tracking and submissions. Updated README.md to guide users on using the new templates for better clarity and consistency in reporting issues and proposing changes.

Add issue and pull request templates

---

index.html
src/css/styles.css

Makes it easier to find the repo.
- Made some semantic changes to the markup (nothing fancy).
- Added the contribute badge that opens Github in a new tab.

Add contribute badge

---

index.html
src/css/styles.css

Reverts wkambale/missingpersons#91

Revert "Add contribute badge"

---

src/css/styles.css
src/js/scripts.js

Please include a summary of the changes and the related issue(s) this PR addresses.
- Add counters to the respective statuses / categories to indicate how many persons for each status
Fixes #(issue)
Please delete options that are not relevant.
Please add any screenshots that demonstrate the changes made.

Add counters to all the available statuses (categories)

---

src/js/analytics.js

- improve color contrast on the charts, and add dynamic rendering of colors based on elementid
Improve color contrast on the charts, and add dynamic choosing of the background colors depending on the elementid.
Please delete options that are not relevant.

Improve analytics colors

---

src/js/scripts.js

-  API was returning 50 records by default. 
Fixes #(issue)
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My changes generate no new warnings
Please add any screenshots that demonstrate the changes made.

Retrieve all records

---

src/js/scripts.js

- Adds back the `API_URL` variable in the `script.js` file
Fixes #(issue)
Please delete options that are not relevant.

HotFix: Add back API_URL
